CREATE DATABASE cookbook;

USE cookbook;

CREATE TABLE IF NOT EXISTS users {
id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(10) NOT NULL,
username VARCHAR(15) NOT NULL,
password VARCHAR(15) NOT NULL
}

CREATE TABLE IF NOT EXISTS recipes {
recipeId INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
recipeName VARCHAR(50) NOT NULL.
recipeSum TEXT NOT NULL,
recipeImg VARCHAR(300) NOT NULL,
recipeDiff VARCHAR(30) NOT NULL,
recipeCat VARCHAR(30) NOT NULL,
recipeIng TEXT NOT NULL,
recipeTime VARCHAR(100) NOT NULL,
recipeServe VARCHAR(100) NOT NULL,
recipeProc TEXT NOT NULL,
recipeStatus TINYINT(1) NOT NULL,
recipeUser VARCHAR(100) NOT NULL,
recipeDelete TINYINT(1) NOT NULL
}

CREATE TABLE IF NOT EXISTS feedback {
feedbackId INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
feedbackContent VARCHAR(300) NOT NULL,
feedbackAssign VARCHAR(200) NOT NULL,
feedbackUser VARCHAR(100) NOT NULL,
feedbackComment VARCHAR(500) NOT NULL
}

CREATE TABLE IF NOT EXISTS archiverecipes {
archiveId INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
archiveName VARCHAR(50) NOT NULL.
archiveSum TEXT NOT NULL,
archiveImg VARCHAR(300) NOT NULL,
archiveDiff VARCHAR(30) NOT NULL,
archiveCat VARCHAR(30) NOT NULL,
archiveIng TEXT NOT NULL,
archiveTime VARCHAR(100) NOT NULL,
archiveServe VARCHAR(100) NOT NULL,
archiveProc TEXT NOT NULL,
archiveUser VARCHAR(100) NOT NULL
}
